### ISSUE TITLE
Playlist name not resetting

### ISSUE THREAD

**Issue by stevetoro** [ThomDavis40/jammming#5]
https://github.com/ThomDavis40/jammming/blob/master/src/components/PlayList/PlayList.js#L25

Currently, when you save a playlist, although your tracklist is getting emptied, the playlist name is not being reset to your default value. 

First, use `value` instead of `defaultValue` as an attribute on the input. 

Second, you should pass the playListName value down from the `App` component as a prop, then you can refer to it in the Playlist as `{this.props.playListName}` so that its name is always rendered dynamically.

**Comment by ThomDavis40** [comment]
Thanks for the suggestion, I now can see the playlist name reset once it has been saved.
